name: data update

on:
  schedule:
    - cron: '5 * * * *' #UTC

jobs:
  data_update:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: deploy/resources
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: clone
        run: git clone --depth 1 https://github.com/covid19-kitakyushu/covid19-data-updater.git data_setup
      - name: npm install
        run: |
          cd $GITHUB_WORKSPACE/data_setup
          npm install
      - name: update
        run: |
          node main.js
      - name: copy json
        run: |
          cd $GITHUB_WORKSPACE
          cp -f ./data_setup/data.json ./data/data.json
          cp -f ./data_setup/news.json ./data/news.json
          rm -rf data_setup
      - name: Create Pull Request @ deploy/resources
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy/resources
          title: Update data
          body: Update data
          commit-message: Update data
